server:
   port: 10080
spring:
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.H2Dialect
            ddl-auto: none
            show-sql: true
   datasource:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
      username: sa
      password: sa
      continue-on-error: true
